# Generated by Django 5.0.6 on 2025-07-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('school', '0002_feetype_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicperiod', verbose_name='Période Académique'),
        ),
    ]
