# Generated by Django 5.0.6 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Enfant'), ('EVALUATION', 'Évaluation à venir'), ('HOMEWORK', 'Devoir à faire'), ('QUIZ', 'Interrogation / Quiz'), ('MESSAGE_TEACHER', "Message de l'enseignant"), ('PAYMENT', 'Statut de Paiement'), ('REPORT_CARD', 'Bulletin Scolaire'), ('GENERAL', 'Général')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
