# Generated by Django 5.0.6 on 2025-06-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_account',
        ),
    ]
