# Generated by Django 5.0.6 on 2025-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_notification_options_student_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Sujet'),
            preserve_default=False,
        ),
    ]
