# Generated by Django 5.0.6 on 2025-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_feetype_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Notes ou détails supplémentaires sur le paiement.', null=True),
        ),
    ]
