# Generated by Django 5.0.6 on 2025-06-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_course_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['school__name', 'academic_period__name', 'name', 'subject__name'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'name', 'subject', 'academic_period')},
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to='school.classe', verbose_name='Classes Associées'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_offered', to='school.subject', verbose_name='Matière'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='classe',
        ),
    ]
