# Generated by Django 5.0.6 on 2025-07-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_payment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est active')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Catégorie de Dépense',
                'verbose_name_plural': 'Catégories de Dépenses',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('PAID', 'Payée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='expenses/proofs/', verbose_name='Preuve de paiement')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('request_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='École')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_requested'],
            },
        ),
    ]
