# Generated by Django 5.0.6 on 2025-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['school__name', 'academic_period__name', 'name', 'subjects__name'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'name', 'academic_period')},
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses_offered', to='school.subject', verbose_name='Matières'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
