# Generated by Django 5.0.6 on 2025-06-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['school__name', 'academic_period__name', 'name'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['school__name', 'academic_period__name', 'name'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classe',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='classes_assigned', to='school.course', verbose_name='Cours associés à cette Classe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportcard',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards_generated', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances_related', to='school.enrollment', verbose_name='Inscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code du Cours'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school', verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'code', 'academic_period')},
        ),
    ]
