# Generated by Django 5.0.6 on 2025-06-27 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_classe_options_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la Classe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'TEACHER'}, related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants de la Classe'),
        ),
    ]
