# Generated by Django 5.0.6 on 2025-06-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_classe_description_classe_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='courses',
        ),
    ]
